### ISSUE TITLE
Beta 0.9.7 Issues

### ISSUE THREAD

**Issue by tsawyer** [AllStarLink/Allmon3#101]
- This URL in the README doesn't exist (there's no tag yet):
`wget https://github.com/AllStarLink/Allmon3/releases/download/rel_0_9_7/allmon3_0.9.7-1_all.deb` 

- Menu.ini:
`2501 RTCM = 'voter.html#2501'      # this goes where expected`
`2501 RTCM = 'allmon3/voter.html'  # this one in the README does not`
`'2501 RTCM' = 'allmon3/voter.html'  # README suggested entry shows single quotes on menu`

- Voter Page gets Stuck
  After going to the voter page, the browser is stuck there. This happens with MacOS Safari, MacOS Chrome and iOS. Clicking another menu item does not update the URL. Closing the Tab seems to be the only way to get the site back.

- Login not prompting for credentials after logout.
- Voter is not updating at settings speed. My sense is the deamon is ok but the web is not keeping up.
 ```
webvpinterval=330
webvpsubsec=y
voterpollinterval=300
voterpollsubsec=y
```
- I don't know if using the # (pound sign) in the URL is part of the issue but could pretty URLs like `/allmon3/voter/2501` and `/allmon2/node/2501` or `/allmon3/nodes/2501,2509` be used?

**Comment by jxmx** [comment]
@tsawyer - Regarding your timing, 300ms is probably unnecessarily aggressive for the web polling side of things. When voterserver.php is running with a "300ms" interval it's not really a 300ms cycle time. With a long-running PHP process, that's just the sleep timer between other work that takes at least that long to complete if not longer. Assuming that the workload itself takes 300ms to complete your full polling interval time is 600ms.  That's largely similar to how asl-votermon operates except that since the connection items are all persistent there's less overhead.

With the web browser, since these execute asynchronously, you're asking JavaScript to have the browser request the data **every** 300ms on the dot over and over and over again whether or not the data is ready. Once you start stacking up the requests, they'll start overwriting each other's data. Try making your webvpinterval be something more like 700ms and see if the results improve.

**Comment by tsawyer** [comment]
Makes sense @jxmx what you are saying about poling vs sleep. Seems polling has a serious disadvantage in that it can step on itself.  Can something be done about that such as waiting for a response before polling again? You did mention that ZMQ wasn't ready for websockets. 

As suggested, I set webvpinterval to 700. Performance did feel any different. Still very slow compared to Allmon2. I don't expect users will find the voter view performs to expectations. But, seeing as this is a beta release, if you would like to release as is we'll see how it goes. Certainly fixing the current navigations problem will help folks get a feel for the voter performance.

**Comment by jxmx** [comment]
Can you be more specific on exactly? What is “slow “? Since I don’t have a voter system I can’t really debug the process to see if there’s something that’s blocking specifically. The biggest issue is that in general web application Architecture in modern times is based around asynchronous event-driven programming.

As I mentioned earlier and then had rejected but maybe I should revisit is, we could do it with a websocket and preserve the event-driven goals of modern web browsers. That’s how the different digital mode dashboards work and seem to work well.


On Apr 16, 2023, at 10:18 AM, Tim Sawyer ***@***.***> wrote:

﻿

Makes sense @jxmx<https://github.com/jxmx> what you are saying about poling vs sleep. Seems polling has a serious disadvantage in that it can step on itself. Can something be done about that such as waiting for a response before polling again? You did mention that ZMQ wasn't ready for websockets.

As suggested, I set webvpinterval to 700. Performance did feel any different. Still very slow compared to Allmon2. I don't expect users will find the voter view performs to expectations. But, seeing as this is a beta release, if you would like to release as is we'll see how it goes. Certainly fixing the current navigations problem will help folks get a feel for the voter performance.

**Comment by tsawyer** [comment]
I'll arrange for a demo of Allmon2 in comparison with the guys up north. What the best way to set this up to coordinate; text, phone call?

- [Allmon3 27439 Voter](https://allmon3.wd6awp.us/allmon3/voter.html#27439)
- [Allmon2 27439 Voter](https://wd6awp.net/allmon/voter.php?node=27439)

**Comment by jxmx** [comment]
We can do that. I can't do it today however. But, in general, what's slow? Allmon2 sees traffic a fraction of a second faster? The charts are getting stuck?

**Comment by tsawyer** [comment]
I would say less then 3 or 4 updates per second is to slow. As you know Allmon2 has a 330 millisecond sleep time between polls. My sense is that the Allmon2 voter view easily keeps up with that rate. 

FYI... The RTCM sends 80 milliseconds of audio, a time stamp and RSSI per packet. So it's safe to assume the voter could switch as often as every 80 milliseconds. The display doesn't need to update that fast but it gives you the idea of it's capabilities.

**Comment by jxmx** [comment]
@tsawyer  Regarding the URLs... I wanted to use the hash mechanism which is common to AJAX web applications to prevent the browser from reloading the pages all the time. /node/NNNN would be interpreted as a new page to be loaded rather than just a change of the internal application state. It'd be trivial enough to set that up in mod_rewrite if you wanted them just for posting elsewhere. But the hash-change logic is pretty integral to the app concept.
