### ISSUE TITLE
Voter Command AMI Output is Arbitrarily Different Than Everything Else

### ISSUE THREAD

**Issue by tsawyer** [AllStarLink/Allmon3#152]
### Result from Allmon3

<img width="1169" alt="Screenshot 2023-07-08 at 9 17 52 AM" src="https://github.com/AllStarLink/Allmon3/assets/1526362/f94e83ca-8930-4f6d-9c83-490505bf6d02">

### Result from Allmon2

<img width="505" alt="Screenshot 2023-07-08 at 9 22 51 AM" src="https://github.com/AllStarLink/Allmon3/assets/1526362/9aea9b3f-df44-4cae-8372-8dfbe8ceae63">

**Comment by jxmx** [comment]
@tsawyer It appears that the `voter *` commands have an arbitrarily different output on Asterisk 1.4 from Asterisk 20. It appears to spit out an arbitrary newline before outputting the command response rather than just starting the response. The parsing logic in `asl_allmon.ami_parser` needs to be updated to account for it while still working for the other commands too.

**Comment by jxmx** [comment]
@tsawyer please pull & test
