### ISSUE TITLE
Add Uptime to Node Heading

### ISSUE THREAD

**Issue by tsawyer** [AllStarLink/Allmon3#162]
Show Asterisk up time from `core show uptime` formatted something like this:

<img width="436" alt="Screenshot 2023-08-24 at 12 29 35 PM" src="https://github.com/AllStarLink/Allmon3/assets/1526362/b4e6fe11-8516-4464-b3a4-e7be78e5efd3">

**Comment by jxmx** [comment]
@tsawyer This requires some thought. I don't want to poll `core show uptime` every interval processing because that's one more command to execute and process on every polling interview. I could fetch it once and let the browser count upwards. The only downside to that is long-running monitors wouldn't "see" a server restart.

**Comment by tsawyer** [comment]
I wouldn't worry about adding a polling command. Limit the uptime command to links list.  Uptime is not needed on the voter display. That will save unnecessary poling.

fyi, I typically set the list display to 800ms or so to prevent missing a second count less often. The voters are set much faster, more like 300ms or so.

**Comment by tsawyer** [comment]
Make it a setting. The default would be off.
